### ISSUE TITLE
How to pass motion to the operator?

### ISSUE THREAD

**Issue by fovj** [zdcthomas/yop.nvim#5]
Hello, I wrote an operator myself, and it works fine. 
Then I realized that I mostly use `<leader>siw`, so I map it directly.
```lua
-- say it operator
local function say_it(lines)
  vim.loop.spawn("say", {
    args = { join(lines, "\n") },
  })
end
op_map({ "n", "v" }, "<leader>s", say_it) -- this works fine.

vim.keymap.set("n", "<leader><leader>s", "<leader>siw")  -- this mapping doesn't work
```

But the mapping not working. Did I do something wrong?

**Comment by zdcthomas** [comment]
Hey, so this is to do with key mappings not using other user key maps by default. In the opts section of your second keymap, set remap to true and you should be gtg. Take a look at these docs for more info https://neovim.io/doc/user/lua.html#vim.keymap.set()

**Comment by fovj** [comment]
> Hey, so this is to do with key mappings not using other user key maps by default. In the opts section of your second keymap, set remap to true and you should be gtg. Take a look at these docs for more info https://neovim.io/doc/user/lua.html#vim.keymap.set()

That's it! it make me like a BOSS 🚀
